### ISSUE TITLE
图片平铺不压缩

### ISSUE THREAD

**Issue by Riunshow** [Riunshow/NoteBook#11]
```css
div {
  height:100%; 
  background-image: url(); 
  background-position: center center; 
  background-size: cover;
}
```

**Comment by setsunadoudou** [comment]
已读！

**Comment by Riunshow** [comment]
```scss
.img-div {
  width: 300px;
  height: 300px;
  position: relative;
  border: 1px solid #e5e5e5;
  margin: 0 5px;

  .img {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;
    margin: auto;
    max-width: 100%;
    max-height: 100%;
  }
}
```
