### ISSUE TITLE
How to change a span to look like a pre with CSS?

### ISSUE THREAD

**Issue by Riunshow** [Riunshow/NoteBook#17]
https://stackoverflow.com/questions/219219/how-to-change-a-span-to-look-like-a-pre-with-css

```css
.like-pre {
  white-space: pre;
  display: block;
}
```
