### ISSUE TITLE
gitea + drone

### ISSUE THREAD

**Issue by Riunshow** [Riunshow/NoteBook#29]
```yaml
version: "3"
networks:
  gitea:
    external: false
services:
  gitea-server:
    image: gitea/gitea:1.15.2
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      - GITEA__database__DB_TYPE=postgres
      - GITEA__database__HOST=postgres-db:5432
      - GITEA__database__NAME=gitea
      - GITEA__database__USER=gitea
      - GITEA__database__PASSWD=gitea
    restart: always
    networks:
      - gitea
    volumes:
      - /home/gitea:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
        - postgres-db
  postgres-db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    networks:
      - gitea
    volumes:
      - /home/gitea/postgres:/var/lib/postgresql/data
  drone-server:
    image: drone/drone:latest
    container_name: drone-server
    ports:
      - "8080:80"
      - "8000:8000"
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/gitea/drone/:/var/lib/drone/:rw
    restart: always
    environment:
      - DRONE_DEBUG=true
      - DRONE_LOGS_DEBUG=true
      - DRONE_GITEA_CLIENT_ID=82442ea3-7698-4b1a-a9f8-3522a7b6f4e9
      - DRONE_GITEA_CLIENT_SECRET=D119aRXhrNl5YT5G7gMbPdW5J4DHv8k3TngqpDHYVxKe
      - DRONE_GITEA_SERVER=http://r.rainbower.life:3000
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SERVER_HOST=r.rainbower.life:8080
      - DRONE_SERVER_PROTO=http
      - DRONE_RPC_SECRET=9c3921e3e748aff725d2e16ef31fbc42
      - DRONE_TLS_AUTOCERT=false
      - DRONE_USER_CREATE=username:rainbower,admin:true
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - gitea
  drone-runner-docker:
    image: drone/drone-runner-docker:latest
    container_name: drone-runner-docker
    ports:
      - "8081:3000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - DRONE_DEBUG=true
      - DRONE_LOGS_DEBUG=true
      - DRONE_RPC_PROTO=http
      - DRONE_RPC_HOST=r.rainbower.life:8080
      - DRONE_RPC_SECRET=9c3921e3e748aff725d2e16ef31fbc42
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_RUNNER_NAME=r.rainbower.life
    restart: always
    networks:
      - gitea
```
