### ISSUE TITLE
面试

### ISSUE THREAD

**Issue by Riunshow** [Riunshow/NoteBook#4]
### css
- css垂直水平居中的几种方式？
- BFC是什么？触发条件是什么？
- 清除浮动

### js
- 什么是原型链？
- 判断数据类型
- 什么是闭包？闭包的问题怎么解决？
- new是怎么实现的？

### http
- 跨域
- 三次握手详情

### html
- 重绘与回流

### Vue
- 生命周期
- 组件传参
- data变化触发哪个生命周期
- vuex中的异步action是怎么实现的
- vue的实现机制是什么？
- 讲讲虚拟dom？

### react
- react与vue的比较
- 在哪个生命周期优化
- redux是什么？
- redux有哪些中间件

___

### 1. css垂直水平居中的几种方式？

- line-height: height

- display: flex 

  ```html
  <div class="box">
    <div class="content">
    </div>
  </div>
  ```
  
  ```css
  .box {
    background-color: #FF8C00;
    width: 300px;
    height: 300px;
    display: flex;
    justify-content: center;
    align-items: center;
  }
  .content {
    background-color: #F00;
    width: 100px;
    height: 100px;
  }
  ```
 
- absolute + transform

  ```html
  <div class="box">
    <div class="content">
    </div>
  </div>
  ```
  ```css
  .box {
    background-color: #FF8C00;
    width: 300px;
    height: 300px;
    position: relative;
  }
  .content {
    background-color: #F00;
    width: 100px;
    height: 100px;
    position: absolute;
    left: 50%;
    top: 50%;
    transform: translate(-50%,-50%);
  }
  ```
### 2. BFC是什么？触发条件是什么
  > 浮动元素和绝对定位元素，非块级盒子的块级容器（例如 inline-blocks, table-cells, 和 table-captions），以及overflow值不为“visiable”的块级盒子，都会为他们的内容创建新的BFC（块级格式上下文）。

  - BFC是一个独立的布局环境，其中的元素布局是不受外界的影响，并且在一个BFC中，块盒与行盒（行盒由一行中所有的内联元素所组成）都会垂直的沿着其父元素的边框排列。

  - float的值不是none。
  - position的值不是static或者relative。
  - display的值是inline-block、table-cell、flex、table-caption或者inline-flex
  - overflow的值不是visible

### 3. 清除浮动
  - 父元素设置 overflow：hidden
  - 使用:after 伪元素
	```css
	.clearfix:after {
		content:"."; 
		display:block; 
		height:0; 
		visibility:hidden; 
		clear:both; 
	}
	```
